{
    "KPlugin": {
        "Authors": [
            {
                "Email": "dvratil@kde.org",
                "Name": "Daniel Vrátil"
            }
        ],
        "Description": "Runner which searches through your contacts",
        "Description[ar]": "مشغّل يبحث في متراسليك",
        "Description[az]": "Kontaktları axtarmaq və açmaq üçün modul",
        "Description[ca@valencia]": "Executor que busca a través dels vostres contactes",
        "Description[ca]": "Executor que cerca a través dels vostres contactes",
        "Description[da]": "Runner som søger efter dine kontakter",
        "Description[de]": "Runner, der Ihre Kontakte durchsucht",
        "Description[el]": "Εκτελεστής αναζήτησης στις επαφές σας",
        "Description[en_GB]": "Runner which searches through your contacts",
        "Description[es]": "Lanzador que busca por sus contactos",
        "Description[et]": "Käivitaja, mis otsib sinu kontaktides",
        "Description[eu]": "Zure kontaktuetan barrena bilatzen duen exekutatzailea",
        "Description[fi]": "Suoritusohjelma, joka etsii yhteystiedoista",
        "Description[fr]": "Module Runner qui recherche dans vos contacts",
        "Description[gl]": "Executor que busca contactos.",
        "Description[hi]": "रनर जो आपके सम्पर्क खोजता है",
        "Description[hsb]": "Program kotryž pyta we Wašich kontaktach",
        "Description[hu]": "Keresés a névjegyek között",
        "Description[ia]": "Cursor que cerca per tu contactos",
        "Description[it]": "Esecutore che cerca tra i contatti",
        "Description[ka]": "დამხმარე პროცესი, რომელიც თქვენი კონტაქტების ძებნაში დაგეხმარებათ",
        "Description[ko]": "연락처를 검색하는 실행기",
        "Description[nl]": "Programma dat uw contactpersonen doorzoekt",
        "Description[nn]": "Køyrar som søkjer etter e-postkontaktar",
        "Description[pl]": "Wyszukuje kontakty",
        "Description[pt]": "Módulo de execução que pesquisa nos seus contactos",
        "Description[pt_BR]": "Módulo de execução que pesquisa nos seus contatos",
        "Description[ru]": "Модуль для поиска и открытия контактов",
        "Description[sk]": "Program, ktorý prehľadáva vaše kontakty",
        "Description[sl]": "Zaganjalnik, ki preišče vaše stike",
        "Description[sr@ijekavian]": "Извођач који тражи кроз ваше контакте",
        "Description[sr@ijekavianlatin]": "Izvođač koji traži kroz vaše kontakte",
        "Description[sr@latin]": "Izvođač koji traži kroz vaše kontakte",
        "Description[sr]": "Извођач који тражи кроз ваше контакте",
        "Description[sv]": "Körprogram som söker igenom kontakter",
        "Description[tr]": "Bağlantılarınızı arayacak olan araç",
        "Description[uk]": "Засіб запуску для пошуку у записах ваших контактів",
        "Description[x-test]": "xxRunner which searches through your contactsxx",
        "Description[zh_CN]": "搜索您的联系人的运行器",
        "Description[zh_TW]": "當搜尋你的聯絡人時執行",
        "EnabledByDefault": true,
        "Icon": "view-pim-contacts",
        "Id": "PIM Contacts Search Runner",
        "License": "LGPL",
        "Name": "PIM Contacts Search",
        "Name[ar]": "البحث في متراسلي PIM",
        "Name[az]": "PİM Kontaktları Axtarışı",
        "Name[ca@valencia]": "Busca de contactes PIM",
        "Name[ca]": "Cerca de contactes PIM",
        "Name[cs]": "Vyhledávání kontaktů PIM",
        "Name[da]": "Søgning i PIM-kontakter",
        "Name[de]": "PIM-Kontaktsuche",
        "Name[el]": "Αναζήτηση επαφών PIM",
        "Name[en_GB]": "PIM Contacts Search",
        "Name[es]": "Búsqueda de contactos PIM",
        "Name[et]": "PIM-i kontaktide otsing",
        "Name[eu]": "PIM kontaktuen bilaketa",
        "Name[fi]": "PIM-yhteystietojen haku",
        "Name[fr]": "Recherche de contacts PIM",
        "Name[gl]": "Busca de contactos",
        "Name[hi]": "पीआईएम सम्पर्क खोज",
        "Name[hsb]": "Pytanje w PIM-kontaktach",
        "Name[hu]": "Névjegykereső",
        "Name[ia]": "Cerca de contactos de PIM",
        "Name[it]": "Ricerca contatti PIM",
        "Name[ka]": "PIM კონტაქტების ძებნა",
        "Name[ko]": "PIM 연락처 검색",
        "Name[nl]": "PIM in contactpersonen zoeken",
        "Name[nn]": "Søk i e-postkontaktar",
        "Name[pl]": "Wyszukiwanie kontaktów ZIO",
        "Name[pt]": "Pesquisa de Contactos PIM",
        "Name[pt_BR]": "Pesquisa de Contatos PIM",
        "Name[ru]": "Поиск контактов в PIM",
        "Name[sk]": "Hľadanie kontaktov PIM",
        "Name[sl]": "Iskanjem PIM po stikih",
        "Name[sr@ijekavian]": "Претрага ПИМ контаката",
        "Name[sr@ijekavianlatin]": "Pretraga PIM kontakata",
        "Name[sr@latin]": "Pretraga PIM kontakata",
        "Name[sr]": "Претрага ПИМ контаката",
        "Name[sv]": "Kontaktsökning i personlig informationshantering",
        "Name[tr]": "PIM Bağlantılarını Ara",
        "Name[uk]": "Пошук у записах контактів PIM",
        "Name[x-test]": "xxPIM Contacts Searchxx",
        "Name[zh_CN]": "个人信息存储联系人搜索",
        "Name[zh_TW]": "PIM 聯絡人搜尋",
        "ServiceTypes": [
            "Plasma/Runner"
        ],
        "Version": "1.0"
    },
    "X-KDE-ConfigModule": "kf@QT_MAJOR_VERSION@/krunner/kcms/kcm_krunner_pimcontacts"
}
